version: 2

work_dir: &work_dir
            ~/repo
jobs:
  DEV-DEPLOYMENT:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: REQUIREMENTS
          command: |
            sudo apt-get update
            sudo apt-get install docker -y
            sudo apt-get install unzip -y && wget https://releases.hashicorp.com/terraform/0.12.16/terraform_0.12.16_linux_amd64.zip
            unzip terraform_0.12.16_linux_amd64.zip -d terraform /usr/local/bin/
      - attach_workspace:
          at: *work_dir
      - run: AWS_ACCESS_KEY_ID_STG=$AWS_ACCESS_KEY_ID_DEV AWS_SECRET_ACCESS_KEY_STG=$AWS_SECRET_ACCESS_KEY_DEV
      - run:
          name: AWS SETUP
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
            aws configure set region $AWS_REGION
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID_DEV
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY_DEV
      - run:
          name: DEPLOY DEV
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV
            export env=${DEV_ENV}
            export AWS_PROFILE=${AWS_PROFILE_DEV}
            echo "ENVIRONMENT :" ${DEV_ENV}
            make init
            make plan
            make apply


workflows:
  version: 2
  main:
    jobs:
    - DEV-DEPLOYMENT:
        filters:
          branches:
            only: master